sudo: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

language: python

python:
  - "3.6"

before_install:
  # For tests running git command
  - git config --global user.name "test"
  - git config --global user.email "test.test@test.com"

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "pre-commit"
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure
      after_success:
      before_install:
    - stage: test
      name: "test"


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

# command to run tests
script:
  - coverage run --source odoo_migrate setup.py test

after_success:
  - coveralls
